name: 'Deploy website on release'

on:
  release:
    types: [published]

jobs:
  forge-deploy:
    name: 'Laravel Forge Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ secrets.WEBSITE_DEPLOYMENT_TRIGGER_URL }}
